### PR TITLE
Full name bug

### PR DESCRIPTION
**Pull request by jnfang**
Full name appears on the profile page and with each question that the user has created
This fixes error raised if first_name or last_name is nil but full_name is called upon loading of those two pages

### CODE REVIEW

**Comment by elliottyates** [comment]
Ok! This does fix the server error, but it does introduce some unexpectedness into the view:

screen shot 2016-01-28 at 7 24 13 pm

Note that the user link shows up as the relative link text (for user with `user_id=1`; I gave that user a blank first name to test the page view).

Unfortunately, it appears we _do_ allow users to sign up with blank names! Crazy. We have two options here:
- fix the display of blank full names and raise a bug for the sign up issue;
- fix the sign up issue in this code packge and not worry too much about fixing the blank name display, because we've at least fixed the server error and won't expect users to be able to sign up with blank names anymore anyway
- (others...?)

I'm partial to the first. There may be another approach here as well: using [string interpolation](http://ruby.bastardsbook.com/chapters/strings/#h-2-4).

So something like this:

```
"#{first_name} #{last_name}".strip
```

could replace the whole `if-end` section, I think.

That would cover this, and we could raise a new bug (please do) for the sign-up, and put it in Doing Next. 

I also noticed, incidentally, that our Profile page is not using our handy `full_name` method -- if you can switch it over to using it as part of this PR that would be great (for keeping things consistent).

**Comment by jnfang** [comment]
To get to the page that you attached in the screenshot, what kind of user sign up did you do? And what is the expected behavior for the label that you mentioned is showing /users/1?

Also, of the two options that you mentioned, is the first option inclusive of the second?

**Comment by elliottyates** [comment]
That page is generated by the qsets#show controller (qsets/show.erb.html). You can use `rake routes` to see what URL would hit that (e.g. `qsets/2`). (Note that root-level qsets also hit `qsets#show` but are routed to a different view, so you'll need to create a sub-qset, create a question, then change that user's first name or last name to `nil` to reproduce.

I'm not sure there's any particular best label for a user's name if it doesn't have a first or last. Your existing approach (returning `nil`) is probably fine, as long as we raise the sign-up bug and fix that. Note that the link helper that generates that offending `/users/1` must just show the URL if its 'link text' resolves to `nil`; another approach would be string interpolation, which would handle the case where a user had a first but not a last name (and vice versa) by showing just that partial component of the name. But I think it's not very important, because at least we're not getting a server error, and really we shouldn't be allowing people to not have a name. :) So the sign-up bug is really the important thing we discovered here!

Let me revise the options I see, and you can add to them if you wish.
1. Make the profile page (`users/show.erb.html`) use `full_name`. Raise a bug for the sign-up page. (Your `User` model code is fine.)
2. Make the profile page (`users/show.erb.html`) use `full_name`. Fix the sign-up page so it validates the name fields (disallows blanks).

So yes, 2 is inclusive of 1.

Thoughts?

**Comment by elliottyates** [comment]
Can you please submit a new PR, with a new branch containing just the commits related to your code? Alternatively you can use this same branch but rebase just the commits related to the new code on top of the current version of master, and force-update your branch on github. Probably the first option (new branch, new commits or cherry-pick commits from this branch) is easier. Let me know how I can help.

**Pull request closed without merging**
