### PR TITLE
removes unused JS libraries and references

### PR DESCRIPTION
**Pull request by elliottyates**
I don't think any of these are used anymore. I tested a bunch of different pages/modals/etc manually.

### CODE REVIEW

**Comment by elliottyates** [comment]
@sarahschachman can I get your thumbs up on this please?

**Comment by elliottyates** [comment]
To test this locally:

```
git fetch origin
git checkout -b elliott/remove_unused_javascript origin/elliott/remove_unused_javascript
git merge master
```

(`origin` is penzance -- if your penzance is something different, e.g. `upstream`, you'll have to change that reference)

**Comment by rckim77** [comment]
test comment

**Comment by rckim77** [comment]
Tested locally and everything works (e.g., scrolling isn't affected). Looks like the jquery files weren't needed!

**Pull request merged**
